version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        volumes:
            - ./db_data:/var/opt/mssql/data
        environment:
            SA_PASSWORD: "Adminadmin1." #Duck you Microsoft
            ACCEPT_EULA: "Y"
